language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - ruby-head
  - 2.0.0
  - jruby-19mode
  - jruby-18mode
  - jruby-head
  - rbx-19mode
  - rbx-18mode
